exclude: ["_scss", "_resources", "_drafts", "Rakefile"]
include: ["_demo-*"]
name: nightpolly.com
url: http://nightpolly.com
description: "Polly Ivanova&rsquo;s blog. Thoughts and front-end experiments published at times."
markdown: redcarpet
paginate: 5
permalink: /:categories/:title
pygments: true
excerpt_separator: ""
